package export

import (
	"bytes"
	"fmt"

	"github.com/go-pdf/fpdf"
	"github.com/swimplan/backend/internal/model"
)

// PdfExporter renders a workout plan as an A4 PDF.
type PdfExporter struct{}

func (e *PdfExporter) Export(plan *model.WorkoutPlan) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 20)
	pdf.AddPage()

	// Title
	pdf.SetFont("Helvetica", "B", 20)
	pdf.CellFormat(0, 12, plan.Name, "", 1, "C", false, 0, "")
	pdf.Ln(2)

	// Subtitle
	pdf.SetFont("Helvetica", "", 12)
	pdf.SetTextColor(100, 100, 100)
	pdf.CellFormat(0, 8, fmt.Sprintf("Total: %dm", plan.TotalMeters), "", 1, "C", false, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(6)

	// Phases
	writePhaseTable(pdf, "Warmup", plan.Warmup)
	writePhaseTable(pdf, "Main Set", plan.MainSet)
	writePhaseTable(pdf, "Cooldown", plan.Cooldown)

	// Footer
	pdf.Ln(8)
	pdf.SetFont("Helvetica", "I", 9)
	pdf.SetTextColor(150, 150, 150)
	pdf.CellFormat(0, 6, "Generated by Swimplan", "", 1, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (e *PdfExporter) ContentType() string  { return "application/pdf" }
func (e *PdfExporter) FileExtension() string { return "pdf" }

func writePhaseTable(pdf *fpdf.Fpdf, title string, items []model.PlanItem) {
	if len(items) == 0 {
		return
	}

	total := 0
	for _, it := range items {
		total += it.Sets * it.Distance
	}

	// Section header
	pdf.SetFont("Helvetica", "B", 13)
	pdf.SetFillColor(240, 240, 240)
	pdf.CellFormat(0, 9, fmt.Sprintf("%s  (%dm)", title, total), "", 1, "L", true, 0, "")
	pdf.Ln(2)

	// Table header
	colWidths := []float64{80, 25, 35, 30}
	headers := []string{"Exercise", "Sets", "Distance", "Rest"}
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetFillColor(230, 235, 245)
	for i, h := range headers {
		pdf.CellFormat(colWidths[i], 7, h, "1", 0, "C", true, 0, "")
	}
	pdf.Ln(-1)

	// Table rows
	pdf.SetFont("Helvetica", "", 10)
	for _, it := range items {
		label := it.Name
		if it.Abbrev != "" {
			label = fmt.Sprintf("%s (%s)", it.Name, it.Abbrev)
		}
		pdf.CellFormat(colWidths[0], 7, label, "1", 0, "L", false, 0, "")
		pdf.CellFormat(colWidths[1], 7, fmt.Sprintf("%d", it.Sets), "1", 0, "C", false, 0, "")
		pdf.CellFormat(colWidths[2], 7, fmt.Sprintf("%dm", it.Distance), "1", 0, "C", false, 0, "")
		rest := ""
		if it.RestSec > 0 {
			rest = fmt.Sprintf("%ds", it.RestSec)
		}
		pdf.CellFormat(colWidths[3], 7, rest, "1", 0, "C", false, 0, "")
		pdf.Ln(-1)
	}
	pdf.Ln(4)
}
